### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by aidanmews** [moj-analytical-services/coffee_roulette_pairs#6]
Ran the following but no 'Round.csv' was returned:

> library(coffeeroulettepairs)
> # Run the random_pairs function. NB the output will be saved in your current working directory
> random_pairs(filename = 'names.csv', unwantedpairs = 'unwantedpairs.csv')
Your current working directory is: /home/aidanmews/coffee roulette. 'Round.csv' will be saved there.
Parsed with column specification:
cols(
  name = col_character()
)
Parsed with column specification:
cols(
  P1 = col_character(),
  P2 = col_character()
)
The following file containing unwanted pairs was updated: unwantedpairs.csv
Parsed with column specification:
cols(
  P1 = col_character(),
  P2 = col_character()
)

**Comment by georginaeaton** [comment]
@aidanmews I had the same issue. Marco is looking into this. I found that the "unwanted pairs" CSV updates so your round should be at the end of that file as a work around for now.

**Comment by aidanmews** [comment]
Thanks @georginaeaton - I think the "unwanted pairs" CSV file doesn't contain all pairings though

**Comment by georginaeaton** [comment]
Thanks @aidanmews - I've added another issue
